<?php


/* DELETE O CONTRATO E AS DEPENDENCIAS ROTA, CAMINHÃO, MOTORISTA, CONTRATO
 * COM BASE NO IDENTIFICADOR DO CONTRATO
 * */

function ExcluiContrato ($id_contrato) {
        
    
    $sql = "SET @ID_CONTRATO = ".$id_contrato.";
            SET @ID_ROTA = (SELECT ID_ROTA FROM PIP_CONTRATO WHERE ID_CONTRATO = @ID_CONTRATO);
            SET @ID_CAMINHAO = (SELECT ID_CAMINHAO FROM PIP_CONTRATO WHERE ID_CONTRATO = @ID_CONTRATO);
            SET @ID_MOTORISTA = (SELECT ID_MOTORISTA FROM PIP_CONTRATO WHERE ID_CONTRATO = @ID_CONTRATO);
            DELETE FROM PIP_CONTRATO WHERE ID_CONTRATO = @ID_CONTRATO;
            DELETE FROM PIP_ROTA WHERE ID_ROTA = @ID_ROTA ;
            DELETE FROM PIP_CAMINHAO WHERE ID_CAMINHAO = @ID_CAMINHAO;
            DELETE FROM PIP_MOTORISTA WHERE ID_MOTORISTA = @ID_MOTORISTA";

}