	<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/core/classe/Classe.PDO.php');

$conexao = Conexao::getInstance();


$lista = array(
'pmsfp@vertentes.com.br',
'marcoantoniocamelo@hotmail.com',
'prefeiturasantamargarida@yahoo.com.br',
'fabiana@bol.com.br',
'janilson.cunha@ibest.com.br',
'siat@boaesperanca.com.br',
'social@riocasca.mg.gov.br',
'comunica11buti@hotmail.com',
'pmreduto@uai.com.br',
'agricultura@perdoes.mg.gov.br',
'psbmv@ig.com.br',
'defesacivil@sabinopolis.m.gov.br',
'planejamento@pratapolis.mg.gov.br',
'convenios@pedroteixeira.mg.gov.br',
'ricamarte06@hotmail.com',
'piedade@prodatanet.com.br',
'pequeri@uai.com.br',
'pmpescador@emitel.com.br',
'secplanprefeituradepedraazulpedraazul@gmail.com',
'gabinete@piraubanet.com.br',
'defesacivilpcandido@gmail.com',
'pmpalma@terra.com.br',
'secretariaobrast4@hotmail.com',
'celiocarneiro@parademinas.mg.gov.br',
'administracao@pecanha.mg.gov.br',
'agricultura@novaporteirinha.mg.gov',
'avezdopovo@uol.com.br',
'gabinete@mg.gov.br',
'felipe_smau@muriae.mg.gov.br',
'obras@miravania.mg.gov.br',
'pmmpilar@terra.com.br',
'nacipraydan@wkve.com.br',
'pmmesquitamg@terra.com.br',
'comdec@luislandia.mg.gov.br',
'secgabinete@moradanova.mg.gov.br',
'sec.admmb@ip3.com.br',
'governomachado@gmail.com',
'pmlp@lagoadaprata.mg.gov.br',
'seagromanga@bol.com',
'pmluis@uai.com.br',
'prefmunilas@rznet.com.br',
'defesacivil@mariadafe.mg.gov.br',
'martcampos@bol.com.br',
'lamartineduarte@adv.oabmg.org.br',
'jequeri@pontenet.com.br',
'prefeiturajoanesia@terra.com.br',
'pmjaponvar@gamil.com',
'viceprefeito@itamogi.mg.gov.br',
'dcpmjacui@netspeedmg.com.br',
'prefeituraity@emitel.com.br',
'gabinete@netmg.com.br',
'pmjp@comnet1.com.br',
'prefeituramunicipaldeibiai@gmail.com',
'armap@gmail.com',
'viceprefeito@itamogi.mg.gov.br',
'comdec.ibertioga@hotmail.com',
'faimbe@hotmail.com',
'ipiacu.segov@hotmail.com',
'edvaldomeioambiente@hotmail.com',
'pmingai@navinet.com.br',
'piapu@ig.com.br',
'administração@itabirinha.mg.gov.br',
'defesacivilervalia@yahoo.com.br',
'prefeito@curraldedentro.mg.gov.br',
'pmferros@uai.com.br',
'gabinete@espdourado.mg.gov.br',
'pmfl@primeisp.com.br',
'pme@imicro.com.br',
'pmgoiana@powerline.com.br',
'secretaria@felixlandia.mg.gov.br',
'pmdurande@bol.com.br',
'pmft@fernandestourinhomg.com.br',
'prefeituradouradoquara@bol.com.br',
'gabprefeito@divinopolis.mg.gov.br',
'sgp2007@hotmail.com',
'pmdelta@terra.com.br',
'defesacivil@cruzilia.mg.gov.br',
'prefeitura@divisaalegre.mg.gov.br',
'pmdivino@uai.com.br',
'dfsantoscrv@hotmail.com',
'pmdivisaalegre@portalpublico.com.br',
'contato@clarodospocoes.mg.gov.br',
'gapm@congonhas.mg.gov.br',
'prefeito@congonhas.mg.gov.br',
'prefeituracorinto@yahoo.com.br',
'pmcassia@cassianet.psi.br',
'prmcoque@vga.matrix.com.br',
'prefeito@conceicaodorioverde.mg.gov.br',
'coroaci@uol.com.br',
'assistenciasocial@pmcoluna.mg.gov',
'samuel.larra@contagem.mg223',
'gabinete@coluna.mg.gov.b',
'prefcarm@vertentes.com.br',
'pmcarai@hotmail.com',
'pmcagabh@terra.com.br',
'pmcatuti@nortecnet.com.br',
'prefeitura.cg@viareal.com.br',
'prefeita@cataguases.mg.gov.br',
'pmc@ufla.br',
'rogerioalcantara@axtelecom.com.br',
'pmee@carmodocajuru.mg.gov.br',
'pmcassia@cassianet.psi.br',
'carmesia@ibest.com.br',
'prefchap@uai.com.br',
'prefeitura@carmonet.psi.br',
'pcmata@xlig.com.br',
'pmce@connect.com.br',
'smas.campanrio@yahoo.com',
'adailton@caboverde.mg.gov.br',
'bonito@comnt.com.br',
'pmcmgab@uai.com.br',
'prefeituracaparao@uai.com.br',
'prefcamp@uai.com.br',
'pmcb@uai.com.br',
'pmcv@navinet.com.br',
'candiasgov@estratus.com.br',
'contpref@uaisol.com.br',
'tespmcb@stratus.com.br',
'pmcaiana@carangola.com.br',
'pmcambuquira@unicom.com.br',
'pmcmobras@benet.psi.br',
'gabinete@prefeituradecambui.com.br',
'pmdcapim@mtzsitenet.com.br',
'juridico@pmburitis.com.br ',
'bjamparo.bh@terra.com.br',
'cadastro@xnext.com.br',
'jhoonmoreira.jn@gmail.com',
'berizal@primeisp.com.br',
'brasiliamg@uai.com.br',
'prefeiturabocaina@ibest.com.br',
'prefeitura@buritis.mg.gov.br',
'semop@buritis.mg.gov.br',
'contato@bocaiuva.mg.gov.br',
'prefeiturabotumirin@bol.com.br',
'arrecadabru@ig.com.br',
'pmbugre@bugre.mg.municipio.org.br',
'prefeiturabm@ig.com.br',
'iprende@denet.psi.br',
'prefbr@micropic.com.br',
'obras@belmirobraga.mg.gov.br ',
'gabinete@almenara.mg.gov.br ',
'gabprefeito@net.com.br',
'compraspmap@alemparaiba.com.br',
'pmabadia@montenet.com.br ',
'pbarao@uai.com.br',
'pmblonga@uai.com.br',
'prefeituradeacaiaca@uai.com.br',
'pmalvdeminas@uai.com.br ',
'prefalbertina@dglnet.com.br',
'jaqued21@yahoo.com',
'pbarao2010@hotmail.com.br',
'pmb@byalnet.com.br ',
'prefmad@uol.com.br ',
'pmbvm@robynet.com.br ',
'prefeituraimores@logosnet.com.br',
'prefeitura@arinosmg.com.br',
'defesacivildesoledadedeminas31@gmail.com',
'gabinetedoprefeito@digimix.com.br',
'pmsjgoiabal@brfree.com.br',
'contato@saopedrodauniao.mg.gov.br',
'adrianobaita@hotmail.com',
'flavioprado@varginha.mg.gov.br',
'pmum@netsite.com.br',
'gabineteprefeitostl@tricor.com.br',
'prefsaosebastiao@yahoo.com.br',
'pmu@prodatanet.com.br',
'virginia@ig.com.br',
'prefsimaopereira@ig.com.br',
'gabinetedoprefeito@pmspu.gov.br',
'pmsjpacui@ig.com.br',
'pmb@net',
':administracao@delfimmoreira.mg.gov.br',
'prefeituradivinolândiamg@gmail.com',
'administração@extrema.mg.gov.br',
'pmgalileia@.com',
'prefgabinete@sbs-net.com.br',
'prefeitura@porteirinha@yahoo.com.br',
'gabinetesaofelix@municipios-mg.org.br',
'sjalegre@municipios-mg.org.br',
'defesaciviltarumirim@hotmail'
);


$sql = 'SELECT cedec_municipio.nome, com_comdec.email 
from cedec_municipio
INNER Join  com_comdec
	on cedec_municipio.id_municipio = com_comdec.id_municipio';


$query = $conexao->query($sql);

?>
<table border="1">

<?php
$key = 1;
foreach ($query as $value) {
	foreach ($lista as $value1) {

		if(strstr($value[1], $value1)){
			print "<tr>";
			echo "<td>".$key."</td><td>".$value[0]."</td><td>".$value1."</td></tr>";
			$key +=1;
		}
	}

}
?>
