<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/core/classe/Classe.PDO.php');

$conexao = Conexao::getInstance();


$lista = "'Cachoeira Dourada',
'Capinópolis',
'Gurinhatã',
'Ipiaçu',
'Ituiutaba',
'Santa Vitória',
'Araguari',
'Araporã',
'Canápolis',
'Cascalho Rico',
'Centralina',
'Indianópolis',
'Monte Alegre de Minas',
'Prata',
'Tupaciguara',
'Uberlândia',
'Abadia dos Dourados',
'Coromandel',
'Cruzeiro da Fortaleza',
'Douradoquara',
'Estrela do Sul',
'Grupiara',
'Iraí de Minas',
'Monte Carmelo',
'Patrocínio',
'Romaria',
'Serra do Salitre',
'Arapuá',
'Carmo do Paranaíba',
'Guimarânia',
'Lagoa Formosa',
'Matutina',
'Patos de Minas',
'Rio Paranaíba',
'Santa Rosa da Serra',
'São Gotardo',
'Tiros',
'Campina Verde',
'Carneirinho',
'Comendador Gomes',
'Fronteira',
'Frutal',
'Itapagipe',
'Iturama',
'Limeira do Oeste',
'Pirajuba',
'Planura',
'São Francisco de Sales',
'União de Minas',
'Água Comprida',
'Campo Florido',
'Conceição das Alagoas',
'Conquista',
'Delta',
'Uberaba',
'Veríssimo',
'Araxá',
'Campos Altos',
'Ibiá',
'Nova Ponte',
'Pedrinópolis',
'Perdizes',
'Pratinha',
'Sacramento',
'Santa Juliana',
'Tapira',
'Carrancas',
'Ijaci',
'Ingaí',
'Itumirim',
'Itutinga',
'Lavras',
'Luminárias',
'Nepomuceno',
'Ribeirão Vermelho',
'Conceição da Barra de Minas',
'Coronel Xavier Chaves',
'Dores de Campos',
'Lagoa Dourada',
'Madre de Deus de Minas',
'Nazareno',
'Piedade do Rio Grande',
'Prados',
'Resende Costa',
'Ritápolis',
'Santa Cruz de Minas',
'Santana do Garambéu',
'São João del-Rei',
'São Tiago',
'Tiradentes',
'Alfredo Vasconcelos',
'Antônio Carlos',
'Barbacena',
'Barroso',
'Capela Nova',
'Caranaíba',
'Carandaí',
'Desterro do Melo',
'Ibertioga',
'Ressaquinha',
'Santa Bárbara do Tugúrio',
'Senhora dos Remédios',
'Acaiaca',
'Barra Longa',
'Dom Silvério',
'Guaraciaba',
'Jequeri',
'Oratórios',
'Piedade de Ponte Nova',
'Ponte Nova',
'Raul Soares',
'Rio Casca',
'Rio Doce',
'Santa Cruz do Escalvado',
'Santo Antônio do Grama',
'São Pedro dos Ferros',
'Sem-Peixe',
'Sericita',
'Urucânia',
'Vermelho Novo',
'Abre Campo',
'Alto Caparaó',
'Alto Jequitibá',
'Caparaó',
'Caputira',
'Chalé',
'Durandé',
'Lajinha',
'Luisburgo',
'Manhuaçu',
'Manhumirim',
'Martins Soares',
'Matipó',
'Pedra Bonita',
'Reduto',
'Santa Margarida',
'Santana do Manhuaçu',
'São João do Manhuaçu',
'São José do Mantimento',
'Simonésia',
'Alto Rio Doce',
'Amparo da Serra',
'Araponga',
'Brás Pires',
'Cajuri',
'Canaã',
'Cipotânea',
'Coimbra',
'Ervália',
'Lamim',
'Paula Cândido',
'Pedra do Anta',
'Piranga',
'Porto Firme',
'Presidente Bernardes',
'Rio Espera',
'São Miguel do Anta',
'Senhora de Oliveira',
'Teixeiras',
'Viçosa',
'Antônio Prado de Minas',
'Barão de Monte Alto',
'Caiana',
'Carangola',
'Divino',
'Espera Feliz',
'Eugenópolis',
'Faria Lemos',
'Fervedouro',
'Miradouro',
'Miraí',
'Muriaé',
'Orizânia',
'Patrocínio do Muriaé',
'Pedra Dourada',
'Rosário da Limeira',
'São Francisco do Glória',
'São Sebastião da Vargem Alegre',
'Tombos',
'Vieiras',
'Astolfo Dutra',
'Divinésia',
'Dores do Turvo',
'Guarani',
'Guidoval',
'Guiricema',
'Mercês',
'Piraúba',
'Rio Pomba',
'Rodeiro',
'São Geraldo',
'Senador Firmino',
'Silveirânia',
'Tabuleiro',
'Tocantins',
'Ubá',
'Visconde do Rio Branco',
'Aracitaba',
'Belmiro Braga',
'Bias Fortes',
'Bicas',
'Chácara',
'Chiador',
'Coronel Pacheco',
'Descoberto',
'Ewbank da Câmara',
'Goianá',
'Guarará',
'Juiz de Fora',
'Lima Duarte',
'Mar de Espanha',
'Maripá de Minas',
'Matias Barbosa',
'Olaria',
'Oliveira Fortes',
'Paiva',
'Pedro Teixeira',
'Pequeri',
'Piau',
'Rio Novo',
'Rio Preto',
'Rochedo de Minas',
'Santa Bárbara do Monte Verde',
'Santa Rita de Ibitipoca',
'Santa Rita de Jacutinga',
'Santana do Deserto',
'Santos Dumont',
'São João Nepomuceno',
'Senador Cortes',
'Simão Pereira',
'Além Paraíba',
'Argirita',
'Cataguases',
'Dona Eusébia',
'Estrela Dalva',
'Itamarati de Minas',
'Laranjal',
'Leopoldina',
'Palma',
'Pirapetinga',
'Recreio',
'Santana de Cataguases',
'Santo Antônio do Aventureiro',
'Volta Grande',
'Bambuí',
'Córrego Danta',
'Doresópolis',
'Iguatama',
'Medeiros',
'Piumhi',
'São Roque de Minas',
'Tapiraí',
'Vargem Bonita',
'Carmo do Cajuru',
'Cláudio',
'Conceição do Pará',
'Divinópolis',
'Igaratinga',
'Itaúna',
'Nova Serrana',
'Perdigão',
'Santo Antônio do Monte',
'São Gonçalo do Pará',
'São Sebastião do Oeste',
'Arcos',
'Camacho',
'Córrego Fundo',
'Formiga',
'Itapecerica',
'Pains',
'Pedra do Indaiá',
'Pimenta',
'Aguanil',
'Campo Belo',
'Cana Verde',
'Candeias',
'Cristais',
'Perdões',
'Santana do Jacaré',
'Bom Sucesso',
'Carmo da Mata',
'Carmópolis de Minas',
'Ibituruna',
'Oliveira',
'Passa Tempo',
'Piracema',
'Santo Antônio do Amparo',
'São Francisco de Paula',
'Abaeté',
'Biquinhas',
'Cedro do Abaeté',
'Morada Nova de Minas',
'Paineiras',
'Pompéu',
'Três Marias',
'Augusto de Lima',
'Buenópolis',
'Corinto',
'Curvelo',
'Felixlândia',
'Inimutaba',
'Joaquim Felício',
'Monjolos',
'Morro da Garça',
'Presidente Juscelino',
'Santo Hipólito',
'Araújos',
'Bom Despacho',
'Dores do Indaiá',
'Estrela do Indaiá',
'Japaraíba',
'Lagoa da Prata',
'Leandro Ferreira',
'Luz',
'Martinho Campos',
'Moema',
'Quartel Geral',
'Serra da Saudade'";


//$lista_st = implode(", ", $lista);


$sql = 'select com_comdec.email from com_comdec
inner join cedec_municipio
on com_comdec.id_municipio = cedec_municipio.id_municipio
where cedec_municipio.nome in ('.$lista.')';

$query = $conexao->query($sql);

?>
<table border="1">

<?php
$key = 1;
foreach ($query as $value) {

	print "<tr>";
    	echo "<td>".$value['email']."</td></tr>";
		$key +=1;
}
?>
