<?php session_start();
	include_once PATH.'/mod_ajuda/func/include_class_pdf.php';

	$_conexao = new ConexaoMysql();
	
	$_login = new Login();
	
	$_login->logado();

$tipoLibera = 'Doação';
$result = Pagamento::relPgto($_GET['nlib']);
$material = Liberacao::ListaProdutosSemPrint($_GET['nlib']);
define('FPDF_FONTPATH','mod_ajuda/plugins/fpdf/font/');
$pdf = new FPDF("P");
$pdf->Open();
$pdf->AddPage();
$pdf->SetFont('Arial','',10);
$pdf->SetMargins(20,20,20);
$pdf->setY("2.25");
$pdf->setX("11.6");
$pdf->image("mod_ajuda/imagem/brasaoMG_80x77.png",20,15,15,15);
$pdf->Ln(10);
$pdf->Cell(0,7, "Estado de Minas Gerais",0,2,"C");
$pdf->Cell(0,5, "Gabinete Militar do Governador",0,2,"C");
$pdf->Cell(0,6, "Coordenadoria Estadual de Defesa Civil",0,1,"C");
$pdf->image("mod_ajuda/imagem/logodefesacivilpng80x77.png",180,15,15,15);
$pdf->Ln(10);
$pdf->Cell(0,7, iconv('utf-8','iso-8859-1','Recibo nº :'.$result['id_pagamento'].'                      Liberação nº :'.$result['id_liberacao']),0,2,"C");
$pdf->Cell(0,7, iconv('utf-8','iso-8859-1','Recebí da Coordenadoria Estadual de Defesa civil - CEDEC/MG, os seguintes materiais por : '.$tipoLibera.''),0,2,"C");
$pdf->Ln(1);
$pdf->Cell(0,7,"",0,2,"C");
$pdf->Cell(0,7,"",0,2,"C");
$pdf->Cell(0,7,"",0,2,"C");
$pdf->Cell(50,5,"",0,0,"C");
$pdf->Cell(30,5,"Nome",1,0,"C");
$pdf->Cell(30,5,iconv('utf-8','iso-8859-1','Descrição'),1,0,"C");
$pdf->Cell(30,5,"Quantidade",1,0,"C");
$pdf->Ln(5);
	for($i=0; $i < count($material); $i++){
		$pdf->Cell(50,5,"",0,0,"C");
		$pdf->Cell(30,5,$material[$i][0],1,0,"C");
		$pdf->Cell(30,5,$material[$i][1],1,0, "C");
		$pdf->Cell(30,5,$material[$i][2],1,0, "C");
		$pdf->Ln(5);		
	}
$pdf->Ln(5);	
$pdf->Cell(180,5,"----------------------------------------------------------------------------------------------------------------------------------------",0,0,"C");
$pdf->Ln(10);
$pdf->Cell(180,5,iconv('utf-8','iso-8859-1','DADOS DO DESTINATÁRIO'),0,0,"C");
$pdf->Ln(10);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Beneficiário        '),0,0,"L");
$pdf->Cell(20,5, ': '.$result['beneficiario'],0,0,"L");
$pdf->Cell(20,5, '                             '.$result['municipio'],0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','CPF/CNPJ       '),0,0,"L");
$pdf->Cell(20,5, ': '.$result['cpf_benef'],0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Endereco       '),0,0,"L");
$pdf->Cell(20,5, ': '.iconv('utf-8','iso-8859-1',$result['endereco']),0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Telefone       '),0,0,"L");
$pdf->Cell(20,5, ': '.$result['tel_dest'],0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Celular       '),0,0,"L");
$pdf->Cell(20,5, ': '.$result['cel_dest'],0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Bairro         '),0,0,"L");
$pdf->Cell(20,5, ': '.iconv('utf-8', 'iso-8859-1', $result['bairro']),0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','      '),0,0,"L");
$pdf->Cell(20,5, ': ',0,0,"L");
$pdf->Ln(5);	
$pdf->Cell(180,5,"----------------------------------------------------------------------------------------------------------------------------------------",0,0,"C");
$pdf->Ln(10);		
$pdf->Cell(180,5,iconv('utf-8','iso-8859-1','RESPONSÁVEL PELA RETIRADA DO MATERIAL'),0,0,"C");
$pdf->Ln(10);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Responsável    :'.$result['responsavel']),0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','RG             :'.$result['nDocumento']),0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','CPF            :'.$result['cpf_resp']),0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Veículo        :'.$result['veiculo'] ),0,0,"L");
$pdf->Ln(5);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Placa          :'.$result['placa']),0,0,"L");
$pdf->Ln(10);
$pdf->Cell(160,5,iconv('utf-8','iso-8859-1',''.$result['municipio']. ', '.DataMysql::dataExtensoDocumento(date('d,m,Y'))),0,0,"R");
$pdf->Ln(15);
$pdf->Cell(180,5,iconv('utf-8','iso-8859-1','--------------------------------------------------------------------'),0,0,"C");
$pdf->Ln(5);	
$pdf->Cell(180,5,iconv('utf-8','iso-8859-1','Assinatura    :').iconv('utf-8','iso-8859-1',$result['responsavel'].''),0,0,"C");
$pdf->Ln(15);
$pdf->Cell(20,5,iconv('utf-8','iso-8859-1','Responsável pelo Preenchimento : '),0,0,"L");
$pdf->Cell(80,5,iconv('utf-8','iso-8859-1',''.Usuario::getNomeId($_SESSION['seguranca']['idUser']).''),0,0,"R");
$pdf->Ln(5);
$pdf->Ln(60);
$pdf->Footer(40,0,RODAPE, 0,1);
$pdf->Output("recibo_".$result['id_pagamento']."-".$result['dtPagto'].".pdf","D");
?>